### ISSUE TITLE
[vol2obj] consider alternative image writing library

### ISSUE THREAD

**Issue by capnramses** [Volograms/vol_cl_tools#2]
The primary interest here is getting ahead security before the tool gets put into eg automated pipelines.

* either fuzz stb_image_write or
* find a reasonable (simple/permissive) substitute image writing library that can output jpeg for vol2obj

**Comment by mattfedo-insight** [comment]
@capnramses - any update on changing the file name or adding the prefix as a parameter?

**Comment by capnramses** [comment]
Hi @mattfedo-insight - I have that over here https://github.com/Volograms/vol_cl_tools/issues/8 - we can definitely do that if it's of use. If you've got any preferences for that please jump over and make a note and I'll see what we can do!
