### ISSUE TITLE
Vols files without normals fail OBJ conversion

### ISSUE THREAD

**Issue by ondrj006** [Volograms/vol_cl_tools#28]
**Describe the bug**
When exporting a VOLS file that doesn't include per-vertex normals the export fails with a message 

`Assertion failed: normals_ptr && "Hey if there are no normals Anton should make sure that is accounted for in the f section", file ..\tools\vol2obj\main.c, line 377`

**Reproducibility**
This happens with every file without normals

**Platform (please complete the following information):**
 This happens on Windows, in the latest version 0.7.0

**Comment by capnramses** [comment]
I think this is the change required to the f (face) section such that it doesn't create an obj with normals
```
      // NOTE(Anton) VOLS winding order is CW (similar to Unity) rather than typical CCW so let's reverse it for OBJ
      if ( normals_ptr ) {
        fprintf( f_ptr, "f %i/%i/%i %i/%i/%i %i/%i/%i\n", c, c, c, b, b, b, a, a, a ); // f v1/vt1/vn1 v2/vt2/vn2 v3/vt3/vn3 ...
      } else {
        fprintf( f_ptr, "f %i/%i %i/%i %i/%i\n", c, c, b, b, a, a );                   // f v1/vt1 v2/vt2 v3/vt3 ...
      }
```
